name: Learning GitHub Script
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    # task 1
      - name: Checkout repo containg the workflow
        uses: actions/checkout@v2
    # Task 2
      - name: Using GitHub Script 1 - Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
              })
      # task 3. Note that task 2/3 can be merge to by just add the script only content below to
      # the next line aft the end of the script in task 2
      - name: Using GitHub Script 2 - Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |              
              github.projects.createCard({
              column_id: {{columnID}},
              content_id: context.payload.issue.id,
              content_type: "Issue"
              });
    # Task 4
      - name: Comment on new issue using a file and adds it only if the issue has a label bug
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
             const fs = require('fs')
             const issueBody = fs.readFileSync(".github/ISSUE_RESPONSES/comment.md", "utf8")
             github.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: issueBody
             })
      
